image: alpine/edge
packages:
  - lua5.3
  - nodejs
  - npm
  - yarn
  - openjdk21-jre
  - bash
  - curl
  - rlwrap
secrets:
  - 897094d7-7887-48dd-ad0e-cc2486c76c25
sources:
  - https://git.sr.ht/~bbuccianti/tones
tasks:
  - envsetup: |
      cat .cloudflare >> .buildenv
  - clojure: |
      curl -L -O https://github.com/clojure/brew-install/releases/latest/download/linux-install.sh
      chmod +x linux-install.sh
      sudo ./linux-install.sh
  - setup: |
      cd tones
      yarn install
  - build: |
      cd tones
      yarn release
  - deploy: |
      cd tones
      npx wrangler pages deploy public/ --project-name=tones
      export RESULT=$(test $? -eq 0 && echo "SUCCEEDED" || echo "FAILED")
      echo "Sending IRC message with: Build $RESULT"
      lua5.3 irc.lua